### ISSUE TITLE
Why SafeArea

### ISSUE THREAD

**Issue by carmas123** [spporan/FlutterOverlayLoader#3]
Hi I use you lib in my app, but after investigate your code I see that you use into the overlay the SafeArea. Now if we need to cover all down widgets with a semi transparent overlay, why we need to skip the notch or bottom padding?

**Comment by desmeit** [comment]
How can I remove the safeArea?

**Comment by spporan** [comment]
Updated with SafeArea customizable flag on this version **`flutter_overlay_loader: ^1.0.3`**
