### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by Tataro** [spporan/FlutterOverlayLoader#4]
Hi,
I got an error if I call `Loader.show(context);` then suddenly call `Loader.hide();`, It will show an error on debug console

![image](https://user-images.githubusercontent.com/5748363/124355782-2bbf3880-dc3d-11eb-9950-818066d72e3b.png)

thanks,

**Comment by 10erlosh** [comment]
same here.
`flutter_overlay_loader: ^0.1.1`

**Comment by spporan** [comment]
Fixed this issue  flutter_overlay_loader: 1.0.0
Thanks for reporting this issue.

**Comment by fabioselau077** [comment]
same problem

**Comment by Achin-verma** [comment]
i am also having the same issue
