### ISSUE TITLE
Cannot Show Overlay Loader

### ISSUE THREAD

**Issue by ayberkcal** [spporan/FlutterOverlayLoader#7]
I cannot show Overlay Loader because of this exception:
`I/flutter (10277): 'package:flutter/src/widgets/overlay.dart': Failed assertion: line 147 pos 12: '_overlay != null': is not true.`
It is very simple case. I call Loader.show before network call but that exception failed. What did I miss?

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19042.1348], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.63.1)
[√] Connected device (3 available)

flutter_overlay_loader: ^1.0.3

**Comment by fabioselau077** [comment]
same problem...
