### ISSUE TITLE
Disable Android Back Button Activity while Loading is Shown

### ISSUE THREAD

**Issue by keithhie** [spporan/FlutterOverlayLoader#9]
Hello,

Is there any way we can disable user interaction i.e. Android's notorious back button while the loader is being shown?

Thank you.

**Comment by spporan** [comment]
You can check loader is being shown or not using the property: ``` Loader.isShown``` and you can prevent back pressed like this snippet:
```dart
    WillPopScope(
        child: //TODO , 
        onWillPop:() async => !Loader.isShown
        )
```

You have to ensusre that you are using updated version  ```flutter_overlay_loader: ^1.0.4```
